prometheus:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    hosts: 
      - prom.fuehrer.me
    tls:
      - secretName: letsencrypt-prod
        hosts:
          - prom.fuehrer.me